Transform: 'AWS::Serverless-2016-10-31'
Resources:

    customerFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Runtime: nodejs12.x
            Handler: index.customerHandler
            CodeUri: ./src
            Events:
                lambdaGetAllCustomers:
                    Type: Api
                    Properties:
                        Path: /api/customers
                        Method: GET
                lambdaGetCustomer:
                    Type: Api
                    Properties:
                        Path: /api/customer/{customerid}
                        Method: GET
                lambdaAddCustomer:
                    Type: Api
                    Properties:
                        Path: /api/customer
                        Method: POST
            Policies:
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/customers'
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/companies'
                                        
    
    productFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Runtime: nodejs12.x
            Handler: index.productHandler
            CodeUri: ./src
            Events:
                lambdaGetAllProducts:
                    Type: Api
                    Properties:
                        Path: /api/products
                        Method: GET
                lambdaGetProduct:
                    Type: Api
                    Properties:
                        Path: /api/product/{productid}
                        Method: GET
                lambdaAddProduct:
                    Type: Api
                    Properties:
                        Path: /api/product
                        Method: POST
            Policies:
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/products'


    companyFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Runtime: nodejs12.x
            Handler: index.companyHandler
            CodeUri: ./src
            Events:
                lambdaGetAllCompanies:
                    Type: Api
                    Properties:
                        Path: /api/companies
                        Method: GET
                lambdaGetCompany:
                    Type: Api
                    Properties:
                        Path: /api/company/{vatregnumber}
                        Method: GET
                lambdaAddCompany:
                    Type: Api
                    Properties:
                        Path: /api/{customerid}/company
                        Method: POST
            Policies:
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/companies'
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/customers'

    budgetFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Runtime: nodejs12.x
            Handler: index.budgetHandler
            CodeUri: ./src
            Events:
                lambdaGetAllBudgets:
                    Type: Api
                    Properties:
                        Path: /api/budgets
                        Method: GET
                lambdaGetBudget:
                    Type: Api
                    Properties:
                        Path: /api/budget/{budgetid}
                        Method: GET
                lambdaAddBudget:
                    Type: Api
                    Properties:
                        Path: /api/{customerid}/budget
                        Method: POST
            Policies:
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/budgets'
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/customers'
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:Query'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/products'
                
    
    customerTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: customers
            AttributeDefinitions:
                -   AttributeName: customerid
                    AttributeType: S
            KeySchema:
                -   AttributeName: customerid
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
    

    productTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: products
            AttributeDefinitions:
                -   AttributeName: productid
                    AttributeType: S
            KeySchema:
                -   AttributeName: productid
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5


    companyTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: companies
            AttributeDefinitions:
                -   AttributeName: vatregnumber
                    AttributeType: S
            KeySchema:
                -   AttributeName: vatregnumber
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
    

    budgetTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: budgets
            AttributeDefinitions:
                -   AttributeName: budgetid
                    AttributeType: S
            KeySchema:
                -   AttributeName: budgetid
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicApi:
    Description: "API Gateway endpoint URL for Prod stage for Customers function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
